Обновление правил
PolitCubes/wiki pull request #7
Opened 2023-08-24 16:31 UTC by officialhaff

Обновленные правила

1. Расширено нулевое (0) правило
2. Внесены официальные ресурсы(контакты) проекта
3. Исправлены некоторые формулировки в пунктах правил
4. Добавлен новый 8(VIII) пункт правил

2023-08-24 18:50 UTC, Clercq requested changes

2023-08-24 18:50 UTC, Clercq commented on docs/general/rules.mdx
> +**1.6.** При введении/изменении крупного пункта правил игроки уведомляются об этом через медиа-ресурсы проекта.
Убрать, можем забыть

2023-08-24 18:52 UTC, Clercq requested changes

2023-08-24 18:52 UTC, Clercq commented on docs/general/rules.mdx
> +Группа Вконтакте : https://vk.com/politcubes
Хорошее описание. 
Но оставить возможность банить по причине пидорас надо.
Если не для всех то хотя бы для меня куба и хоруса.
Почему? 
Потому что я не собираюсь спорить с токсиком 50 минут и доказывать ему что он не прав потому что античит детектнул изменение клиента

2023-08-24 18:54 UTC, Anon8281 commented on docs/general/rules.mdx
> +**2.1.** Оплата доната производится только через официальные медиа-ресурсы проекта, иные площадки не допускаются.
Nani sore? Медиа-ресурсы? Только группа и сайт по факту

2023-08-24 18:54 UTC, Anon8281 commented on docs/general/rules.mdx
> +**1.2.** Обходите стороной темы политики, религии, национальных интересов и подобных “горячих” тем. Такое здесь лучше не только не обсуждать, но и не затрагивать в принципе каким-либо образом, чтобы
Обходить тему политики на политическом сервере? Звучит забавно

2023-08-24 18:57 UTC, Anon8281 commented
Зачем везде убирать заглавную букву у Администрации?)

2023-08-24 18:58 UTC, Anon8281 commented on docs/general/rules.mdx
> +## VIII. Правила голосового чата ##
Имеет смысл только при его наличии

2023-08-24 18:59 UTC, Anon8281 commented on docs/general/rules.mdx
> +Группа Вконтакте : https://vk.com/politcubes
На право бана без излишних объяснений я специально 1.3 вводил: `Администрация игрового сервера, а также любое автоматическое средство, созданное Администрацией, имеют полное право применять любые меры для обеспечения нормального игрового процесса.`

> Хорошее описание. Но оставить возможность банить по причине пидорас надо. Если не для всех то хотя бы для меня куба и хоруса. Почему? Потому что я не собираюсь спорить с токсиком 50 минут и доказывать ему что он не прав потому что античит детектнул изменение клиента

2023-08-24 18:59 UTC, luckybl0ck commented on docs/general/rules.mdx
> +**1.2.** Обходите стороной темы политики, религии, национальных интересов и подобных “горячих” тем. Такое здесь лучше не только не обсуждать, но и не затрагивать в принципе каким-либо образом, чтобы
Чат будет пуст.

2023-08-24 18:59 UTC, officialhaff commented on docs/general/rules.mdx
> +**1.2.** Обходите стороной темы политики, религии, национальных интересов и подобных “горячих” тем. Такое здесь лучше не только не обсуждать, но и не затрагивать в принципе каким-либо образом, чтобы
Понял, ерунду написал

2023-08-24 19:00 UTC, officialhaff commented on docs/general/rules.mdx
> +## VIII. Правила голосового чата ##
Голосовой чат не планируется, правильно понял?

2023-08-24 19:03 UTC, Clercq commented on docs/general/rules.mdx
> +## VIII. Правила голосового чата ##
Пока нет чата, не знаю, захотим ли включать. Он на UDP протоколе пашет, если отркыть UDP завалят сразу же сервак

2023-08-24 19:03 UTC, officialhaff commented on docs/general/rules.mdx
> +Группа Вконтакте : https://vk.com/politcubes
> На право бана без излишних объяснений я специально 1.3 вводил: `Администрация игрового сервера, а также любое автоматическое средство, созданное Администрацией, имеют полное право применять любые меры для обеспечения нормального игрового процесса.`
> 
> > Хорошее описание. Но оставить возможность банить по причине пидорас надо. Если не для всех то хотя бы для меня куба и хоруса. Почему? Потому что я не собираюсь спорить с токсиком 50 минут и доказывать ему что он не прав потому что античит детектнул изменение клиента

В конце  введения добавил про это строчку строчку :
**В исключительных случаях администрация проекта оставляет за собой право блокировки аккаунта или введения иных санкций в отношении игрока с обязательным оповещением о причине такой блокировки.**

2023-08-24 19:05 UTC, officialhaff commented
> Зачем везде убирать заглавную букву у Администрации?)

2023-08-24 19:06 UTC, Clercq commented on docs/general/rules.mdx
> +Группа Вконтакте : https://vk.com/politcubes
Причины лишнее. бан по железу не отображает причину блокировки. Писать в личку типу за что бан я не хочу.

2023-08-24 19:08 UTC, officialhaff commented on docs/general/rules.mdx
> +Группа Вконтакте : https://vk.com/politcubes
> Причины лишнее. бан по железу не отображает причину блокировки. Писать в личку типу за что бан я не хочу.

Понял

2023-08-24 19:10 UTC, officialhaff commented on docs/general/rules.mdx
> +## VIII. Правила голосового чата ##
Значит можно объединить текстовой/голосовой в одно правило

2023-08-24 19:11 UTC, officialhaff commented
Еще заметил, что не указаны сроки наказания за нарушение правил

Они где-то оговариваются или админы делают по своим меркам?

2023-08-24 19:11 UTC, Anon8281 commented
> Еще заметил, что не указаны сроки наказания за нарушение правил
> 
> Они где-то оговариваются или админы делают по своим меркам?

Само собой, по своему усмотрению

2023-08-24 19:14 UTC, Anon8281 commented
Хафф, а ты коммитишь вообще свои правки?

2023-08-24 19:15 UTC, officialhaff commented
> Хафф, а ты коммитишь вообще свои правки?

В плане?

Дропаю по файлам

2023-08-25 12:27 UTC, Anon8281 requested changes

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +**2.4.** В случае нарушения правил, Администрация оставляет за собой право лишить игрока донат-привилегии.
Лишняя запятая в строчке 
```suggestion
**2.4.** В случае нарушения правил Администрация оставляет за собой право лишить игрока донат-привилегии.
```

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +**5.1.** Город может прекратить свое существование, если мэр города нарушит какой-либо пункт правил.
```suggestion
**5.1.** По решению Администрации город может прекратить свое существование, если его мэр каким-либо образом нарушит правила.
```

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> -**1.5.** Администрация проекта не понимает любого юмора.
Это правило существовало не просто так. Игрокам не стоит думать о возможности оправдать свои неадекватные (прим. нарушающие правила) действия шуткой

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
Обычно к пользователям относятся на Вы.
```suggestion
>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете решение несправедливым, то его можно обжаловать в личных сообщениях группы "Вконтакте" : https://vk.com/politcubes в течение трех дней или подать заявку на разбан. В исключительных случаях Администрация проекта оставляет за собой право блокировки аккаунта или введения иных санкций в отношении игрока без объяснения причин.
```

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
Заявка на разбан это who? Тут имеется в виду платный? Не совсем прозрачно

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> -**4.6.** Игроки - творцы, им позволено делать с окружающим миром все что им пожелается, однако не допускается необоснованная порча ландшафта, строительство фаллосов и лавакастов в пустоши, особенно в
С одной стороны, прошлая версия этого правила была слишком вальяжна. С другой же, сейчас имеем отсутствие примеров и непрозрачность его применения. Вопрос этот стоит обдумать (и ведь далеко не первый раз)

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +>Учтите, что «вандализм» по вашей вине не наказывается: воровство ресурсов людьми не из вашего города в результате ошибок в настройке привата и воровство ресурсов людьми, находящимся в вашем списке д
>`Людьми, находящимся`? Вроде как творительный падеж этого слова именно `находящимися` 
https://ru.wiktionary.org/wiki/находящийся
>`Людьми, вошедшими` к тому же

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +>Учтите, что «вандализм» по вашей вине не наказывается: воровство ресурсов людьми не из вашего города в результате ошибок в настройке привата и воровство ресурсов людьми, находящимся в вашем списке д
```suggestion
>Учтите, что «вандализм» по вашей вине не наказывается: воровство ресурсов людьми не из вашего города в результате ошибок в настройке привата и воровство ресурсов людьми, находящимися в вашем списке друзей; воровство ресурсов людьми, вошедшими в ваш город из-за его открытого статуса; отказ регента возвращать звание мэра/короля; диверсия/гриф города советником/ассистентом. Нужно грамотно настраивать чанки и выбирать управленцев.
```

2023-08-25 12:27 UTC, Anon8281 commented on docs/general/rules.mdx
> +**б)**  Для объявления войны вы должны иметь веское основание, противоречащая проводимой вашим государством политикой.
Основание обязательно должно противоречить (забыта частица `не`)? +Беды со склонениями

2023-08-25 12:47 UTC, officialhaff commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
> Заявка на разбан это who? Тут имеется в виду платный? Не совсем прозрачно

Как происходит процедура разблокировки? Куда нужно написать/обратиться для этого? И есть ли платный вариант разблокировки(Помню, что был когда-то)?

2023-08-25 12:50 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
Судя про слова про заявку на разбан, имелся в виду явно не бесплатный (хотя про это и не сказано). Платный вариант разблокировки остаётся до сих пор, верно. Снять обычный бан можно и в автоматическом режиме, но бан по железу точно исключительно через обсуждение с Администрацией

2023-08-25 13:01 UTC, officialhaff commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
> Судя про слова про заявку на разбан, имелся в виду явно не бесплатный (хотя про это и не сказано). Платный вариант разблокировки остаётся до сих пор, верно. Снять обычный бан можно и в автоматическом режиме, но бан по железу точно исключительно через обсуждение с Администрацией

Тогда можно изменить строчку на : 

> Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообщениях группы Вконтакте : https://vk.com/politcubes в течение трех дней, либо приобрести услугу разблокировки.

>В тех случаях, когда блокировка дается навсегда(по железу), разблокировать доступ можно только исключительно через группу Вконтакте

2023-08-25 13:04 UTC, officialhaff commented on docs/general/rules.mdx
> +>Учтите, что «вандализм» по вашей вине не наказывается: воровство ресурсов людьми не из вашего города в результате ошибок в настройке привата и воровство ресурсов людьми, находящимся в вашем списке д
Перепутал ед.ч с мн.ч
![Screenshot_61](https://github.com/PolitCubes/wiki/assets/59340775/39b043b5-1a1a-4dd7-a87b-c26ba6f58b3f)

2023-08-25 13:06 UTC, officialhaff commented on docs/general/rules.mdx
> -**1.5.** Администрация проекта не понимает любого юмора.
> Это правило существовало не просто так. Игрокам не стоит думать о возможности оправдать свои неадекватные (прим. нарушающие правила) действия шуткой

Такая трактовка подойдет?
![Screenshot_62](https://github.com/PolitCubes/wiki/assets/59340775/03b1d233-aff7-48a3-ba31-ddb60f54ef74)

2023-08-25 13:16 UTC, officialhaff commented on docs/general/rules.mdx
> +**б)**  Для объявления войны вы должны иметь веское основание, противоречащая проводимой вашим государством политикой.
> Основание обязательно должно противоречить (забыта частица `не`)? +Беды со склонениями

Такая трактовка подойдет? :
![Screenshot_62](https://github.com/PolitCubes/wiki/assets/59340775/cd328a03-09b3-469d-960b-29fac012aeb7)

2023-08-25 14:09 UTC, officialhaff commented on docs/general/rules.mdx
> -**4.6.** Игроки - творцы, им позволено делать с окружающим миром все что им пожелается, однако не допускается необоснованная порча ландшафта, строительство фаллосов и лавакастов в пустоши, особенно в
Переформулировал :
![Screenshot_64](https://github.com/PolitCubes/wiki/assets/59340775/7978287f-31c4-4acb-a416-88667dcd91e4)

2023-08-25 21:58 UTC, Anon8281 commented on docs/general/rules.mdx
> -**1.5.** Администрация проекта не понимает любого юмора.
Излишняя конкретика, как мне кажется

2023-08-25 22:04 UTC, Anon8281 requested changes

2023-08-25 22:04 UTC, Anon8281 commented on docs/general/rules.mdx
> +**5.5.** Отсутствие какой-либо внятной инфраструктуры города (Пример: город с огромным приватом, состоящий из ферм и сундуков) может привести к санкциям, вплоть до распривата. Правило не распространя
**_Инфраструктура - совокупность учреждений, систем управления, связи и т. п., обеспечивающая деятельность общества или какой-то его сферы._**

Чем тебе так слово "структура" не угодило?

2023-08-25 22:04 UTC, Anon8281 commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом и тому подобное запрещены.
Подумать бы стоило, но я нахожу эту формулировку абсолютно непрозрачной. `Тому подобное` - очень тонкая вещь, а чат модерируют в основном хелперы, далеко не все из которых будут опытными

2023-08-26 07:49 UTC, officialhaff commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом и тому подобное запрещены.
По сути, ПоДоБнОе сообщение, как раз и является злоупотреблением капсом, либо можно привязать к правилу : 

Запрещается злоупотребление поочередно верхнего и нижнего регистра(ПоДоБнОе сообщение)

2023-08-26 07:50 UTC, officialhaff commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом и тому подобное запрещены.
Еще хотел уточнить по поводу написания транслитом

Он разрешен или нет?

2023-08-26 07:53 UTC, officialhaff commented on docs/general/rules.mdx
> +**5.5.** Отсутствие какой-либо внятной инфраструктуры города (Пример: город с огромным приватом, состоящий из ферм и сундуков) может привести к санкциям, вплоть до распривата. Правило не распространя
Инфраструктура больше подходит к описанию и деятельности города(что там должно быть)

Структура также предполагает об этом, но недостаточно описана(что там должно быть)

2023-08-26 07:54 UTC, officialhaff commented on docs/general/rules.mdx
> +>3. Намеренная порча ландшафта с целью гриферства(лавакасты, большие столбы и стены и т.п)
Понял

2023-08-26 21:57 UTC, Anon8281 commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом и тому подобное запрещены.
Транслит может являться латинизированной версией русского языка, доступной людям без кириллической раскладки и умения слепой печати. Не запрещаю. В конце концов, муты по причине пидорас тоже никто не отменял

2023-08-27 08:02 UTC, officialhaff commented on docs/general/rules.mdx
> +>3. Намеренная порча ландшафта с целью гриферства(лавакасты, большие столбы и стены и т.п)
Тогда можно изменить на : 

(Под необоснованной порчей ландшафта стоит понимать)

2023-08-27 23:28 UTC, Anon8281 requested changes

2023-08-27 23:28 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
Не каждый пермач по железу, но каждый бан по железу вечный

2023-08-27 23:28 UTC, Anon8281 commented on docs/general/rules.mdx
> +**4.1.** Торговля ведется на свой страх и риск. Если Вас убили или обманули — это Ваша вина.
Мб прямо сюда дописать запрет про запрет обмана хелперами в примечание

2023-08-27 23:28 UTC, Anon8281 commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом, использование поочередно верхнего и нижнего регистра(ПоДоБнЫе сОоБщЕнИя) запрещены.
Поочерёдное использование запрещено только при злоупотреблении. Первоначальный смысл искажён

2023-08-28 06:21 UTC, officialhaff commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
Не совсем понял

2023-08-28 06:23 UTC, officialhaff commented on docs/general/rules.mdx
> +**4.1.** Торговля ведется на свой страх и риск. Если Вас убили или обманули — это Ваша вина.
Что хелперы не могут наебывать? Мб стоит добавить, так как все же они являются частью Администрации

2023-08-28 11:20 UTC, officialhaff commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом, использование поочередно верхнего и нижнего регистра(ПоДоБнЫе сОоБщЕнИя) запрещены.
> Поочерёдное использование запрещено только при злоупотреблении. Первоначальный смысл искажён

Можно изменить формулировку на : 

Запрещен флуд, спам, чрезмерное использование капса(верхнего регистра), а также злоупотребление поочередно верхнего и нижнего регистра(ПоДоБнЫе сОоБщЕнИя).

2023-08-28 20:01 UTC, Anon8281 commented on docs/general/rules.mdx
> +**4.1.** Торговля ведется на свой страх и риск. Если Вас убили или обманули — это Ваша вина.
> Что хелперы не могут наебывать? Мб стоит добавить, так как все же они являются частью персонала

Наебать-то могут. Но хелперки лишатся

2023-08-28 20:02 UTC, Anon8281 commented on docs/general/rules.mdx
> +**7.2** Флуд, спам, злоупотребление капсом, использование поочередно верхнего и нижнего регистра(ПоДоБнЫе сОоБщЕнИя) запрещены.
В таком случае первое слово не должно быть "Запрещены"?

2023-08-28 20:10 UTC, Anon8281 requested changes

2023-08-28 20:10 UTC, Anon8281 commented on docs/general/rules.mdx
> -**1.5.** Администрация проекта не понимает любого юмора.
Лучше вернуть старую формулировку, конкретика тут излишня

2023-08-28 20:10 UTC, Anon8281 commented on docs/general/rules.mdx
> +>3. Намеренная порча ландшафта с целью гриферства(лавакасты, большие столбы и стены и т.п)
Предложил одно, но коммитнул другое? Тогда уж `являются`

2023-08-28 20:10 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
Зачем пробел между словом и двоеточием

2023-08-28 20:10 UTC, Anon8281 commented on docs/general/rules.mdx
> +> Персонал проекта(Хелперы) не могут использовать любые методы обмана или мошенничества при торговле с игроками. Это включает в себя использование скрытых комиссий, ложных скидок и других нечестных с
Конкретика тут лишняя, потому что создаёт ещё больше спорных ситуаций. Ложные скидки - это основа маркетинга, к примеру

2023-08-28 20:11 UTC, Anon8281 commented on docs/general/rules.mdx
> +> Персонал проекта(Хелперы) не могут использовать любые методы обмана или мошенничества при торговле с игроками. Это включает в себя использование скрытых комиссий, ложных скидок и других нечестных с
`Персонал проекта(Хелперы)` стоило бы заменить на просто `Хелперы`. Про стафф по умолчанию знают только сами хелперы и админы

2023-08-28 20:13 UTC, Anon8281 commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
Пермач не по железу тоже можно снять за деньги в автоматическом режиме, ты меня неправильно понял

2023-08-28 20:40 UTC, officialhaff commented on docs/general/rules.mdx
> -**1.5.** Администрация проекта не понимает любого юмора.
Хорошо

2023-08-28 20:42 UTC, officialhaff commented on docs/general/rules.mdx
> +> Персонал проекта(Хелперы) не могут использовать любые методы обмана или мошенничества при торговле с игроками. Это включает в себя использование скрытых комиссий, ложных скидок и других нечестных с
Понял

2023-08-28 20:43 UTC, officialhaff commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
> Зачем пробел между словом и двоеточием

Отступ нужен для выделения ссылки, не более

2023-08-28 20:53 UTC, officialhaff commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если Вы считаете, что решение было несправедливым, то его можно обжаловать в личных сообще
> Пермач не по железу тоже можно снять за деньги в автоматическом режиме, ты меня неправильно понял

Тогда предпоследнее предложение можно убрать :

`В тех случаях, когда блокировка дается навсегда, разблокировать доступ можно только через группу Вконтакте.`

А что касательно бана по железу, то есть последнее правило в нулевом правиле :

`В исключительных случаях Администрация проекта оставляет за собой право блокировки аккаунта или введения иных санкций в отношении игрока без объяснения причин.` + пункт 1.3

2023-08-30 19:41 UTC, Anon8281 commented
Убери везде пробелы между словами и двоеточиями

2023-08-30 19:55 UTC, Clercq commented on docs/general/rules.mdx
> +>В урегулировании конфликтов и толковании правил проекта последнее слово всегда остается за Администратором. Если ты считаешь, что решение было несправедливым, то можно обжаловать его в личных сообще
Давайте все-таки распишем ситуации конкретные.

Во-первых, если разблокировка доступна к покупке, это отобразится на сайте(мы скрываем этот продукт если аккаунт не заблокирован, как защита от случайного клика)
Во-вторых, если разблокировка доступна к покупке это не <<железный>> бан.
В-третьих я осознаю что у нас не всегда работает личный кабиент(автодонатка), поэтому давайте распишем отдельно что в случае ручной продажи администрация блаблабла может не продавать разбан
В-четвертых в силу первых трех пунктов упоминание <<железного>> предлагаю заменить на любую другую формулировку которая не относится к понятию блокировки по железу

2023-09-01 20:44 UTC, merged